analyzer:
  errors:
    avoid_print: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    use_key_in_widget_constructors: ignore

include: package:flutter_lints/flutter.yaml

linter:
  rules: